In [1]:
import numpy as np

In [2]:
# Column vectors
x = np.array([[2],
              [3],
              [5]])

v = np.array([[3],
              [0],
              [4]])

# x^T v  (1×3 @ 3×1 → scalar 1×1)
xtv = x.T @ v         
print(xtv)              

# x v^T  (3×1 @ 1×3 → 3×3 matrix)
xvt = x @ v.T
print(xvt)


[[26]]
[[ 6  0  8]
 [ 9  0 12]
 [15  0 20]]


In [3]:
A = np.array([[4, 1, 0, 2],
              [2, 0, 1, 3]])

b = np.array([[3],
              [0],
              [5],
              [1]])

print(A.shape) 
print(b.shape) 

c = A @ b    
print(c)



(2, 4)
(4, 1)
[[14]
 [14]]


In [4]:
A = np.array([[4, 1, 0, 2],
              [2, 0, 1, 3]])

B = np.array([[3, 2, 0],
              [0, 4, 2],
              [5, 0, 1],
              [1, 3, 4]])

print(A.shape)  # (2, 4)
print(B.shape)  # (4, 3)

C = A @ B     
print(C)


(2, 4)
(4, 3)
[[14 18 10]
 [14 13 13]]


In [5]:
w = np.array([2, 4, 3, 1])  

norm_w = np.linalg.norm(w, ord=2)
print(norm_w)


5.477225575051661


In [6]:
u = np.array([5, 0, 0])

u_norm = np.linalg.norm(u)
u_unit = u / u_norm

print(u_unit) 


[1. 0. 0.]


In [7]:
# 2b

B = np.array([[3, 2, 0],
              [0, 4, 2],
              [5, 0, 1],
              [1, 3, 4]])

sub = B[1:3, 1:2]   # rows 1 and 2 (Python slice stops BEFORE 3)
                    # column 1 only (slice 1:2 keeps only column 1)
print(sub)


[[4]
 [0]]


In [8]:
# 2c

def dot(v1, v2):
    """
    Compute the dot product of two NumPy arrays v1 and v2
    without using np.dot or np.matmul.
    """

    total = 0.0
    for a, b in zip(v1, v2):
        total += a * b
    return total


In [9]:
import numpy as np

x = np.array([2, 3, 5])
v = np.array([3, 0, 4])

print(dot(x, v))


26.0


In [10]:
#2d

import numpy as np

data = np.array([
    [1, 17,  9],
    [2, 21, 10],
    [3, 12, 17]
])

print(data.shape)



(3, 3)


In [11]:
data[:, 1:3]

np.dot(data[:, 1:3], np.array([[1], [1]]))



array([[26],
       [31],
       [29]])

In [12]:
#2e correct
def transform(data):
    return np.dot(data[:, 1:3], np.array([[1], [1]]))

data = np.array([
    [1, 17,  9],
    [2, 21, 10],
    [3, 12, 17]
])

print(transform(data))


[[26]
 [31]
 [29]]
